"use client";
import Link from "next/link";
import { ArrowUpRight, Search, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { CrewLogo } from "./crew-logo";
import { recruitmentLabels, type Crew, type RecruitmentStatus } from "@/lib/crews/crews";
import styles from "./crew-directory.module.scss";
type Filter="all"|RecruitmentStatus;
export function CrewDirectory({crews}:{crews:Crew[]}){
 const [filter,setFilter]=useState<Filter>("all"),[query,setQuery]=useState("");
 const visible=useMemo(()=>crews.filter(crew=>(filter==="all"||crew.recruitment===filter)&&`${crew.name} ${crew.location} ${crew.style.join(" ")} ${crew.languages.map(language=>`${language.name} ${language.code}`).join(" ")}`.toLowerCase().includes(query.toLowerCase())),[crews,filter,query]);
 const totalMembers=crews.reduce((sum,crew)=>sum+crew.memberCount,0),recruiting=crews.filter(crew=>crew.recruitment==="recruiting").length;
 return <main className={styles.page}>
  <section className={styles.hero}><span className={styles.eyebrow}>The community, organised</span><h1>Find your<br/><em>people.</em></h1><p>Discover crews, watch their latest edits and find the skaters you want to roll with.</p><div className={styles.stats}><span><strong>{crews.length}</strong> active crews</span><span><strong>{totalMembers}</strong> skaters</span><span><strong>{recruiting}</strong> recruiting now</span></div></section>
  {crews.length>0&&<section className={styles.social}><div className={styles.socialIntro}><div><span className={styles.eyebrow}>Crew pulse</span><h2>What’s happening.</h2></div><p>New crews, fresh identities and community updates.</p></div><div className={styles.stories} aria-label="Recently active crews">{crews.map(crew=><Link href={`/crews/${crew.slug}`} key={crew.id}><span style={{"--crew-accent":crew.accent} as React.CSSProperties}><CrewLogo initials={crew.initials} accent={crew.accent} imageUrl={crew.logoUrl} size="medium"/></span><strong>{crew.name}</strong><small>{crew.recruitment==="recruiting"?"Recruiting":"View crew"}</small></Link>)}</div></section>}
  <section className={styles.directory} id="discover"><div className={styles.toolbar}><div className={styles.filters} aria-label="Filter crews">{(["all","recruiting","invite-only","closed"] as Filter[]).map(value=><button key={value} data-active={filter===value} onClick={()=>setFilter(value)}>{value==="all"?"All crews":recruitmentLabels[value]}</button>)}</div><label className={styles.search}><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search crews, languages, regions…"/></label></div><div className={styles.sectionHeading}><div><span>Community crews</span><h2>{crews.length?"Make some noise.":"The first crew starts here."}</h2></div><small>{visible.length} crews shown</small></div>
   <div className={styles.grid}>{visible.map((crew,index)=><Link className={styles.card} href={`/crews/${crew.slug}`} key={crew.id} style={{"--crew-accent":crew.accent} as React.CSSProperties}><div className={styles.cardTop}><CrewLogo initials={crew.initials} accent={crew.accent} imageUrl={crew.logoUrl} size="medium"/><span className={styles.status} data-status={crew.recruitment}><i/>{recruitmentLabels[crew.recruitment]}</span></div><div className={styles.cardNumber}>{String(index+1).padStart(2,"0")}</div><div className={styles.cardBody}><h3>{crew.name}</h3><p>{crew.tagline}</p><div className={styles.tags}>{crew.style.map(tag=><span key={tag}>{tag}</span>)}</div></div><div className={styles.cardSignals}><div className={styles.languages} aria-label={`Languages spoken: ${crew.languages.map(language=>language.name).join(", ")}`}><small>Languages</small>{crew.languages.map(language=><span title={language.name} key={language.code}>{language.flag}<i>{language.name}</i></span>)}</div>{crew.discord&&<span className={styles.discordCount}>Discord · {crew.discord.memberCount?.toLocaleString()} members</span>}</div><div className={styles.cardFooter}><span><Users/> {crew.memberCount} members</span><span>{crew.location}</span><ArrowUpRight/></div></Link>)}</div>
   {!visible.length&&<div className={styles.empty}>{crews.length?"No crews match that search.":<><strong>No crews yet.</strong><span>Create yours from your account and it will appear here.</span><Link href="/account#create-crew">Create a crew <ArrowUpRight/></Link></>}</div>}
  </section>
 </main>;
}
