/* eslint-disable @next/next/no-img-element */
import {notFound} from "next/navigation";
import {requireStudioUser} from "@/lib/studio/auth";
import {deleteComment,deleteMedia,deleteSpot,saveSpot,setMediaCover,setMediaPublished} from "../actions";
import styles from "../../studio.module.scss";

export default async function EditSpot({params}:{params:Promise<{id:string}>}){
    const {id}=await params,{supabase}=await requireStudioUser();
    const [{data:spot},{data:maps},{data:districts},{data:reviews},{data:media},{data:comments}]=await Promise.all([supabase.from("map_spots").select("*").eq("id",id).single(),supabase.from("skate_maps").select("id,name").order("name"),supabase.from("map_districts").select("id,map_id,name").order("name"),supabase.from("spot_reviews").select("rating").eq("spot_id",id),supabase.from("spot_media").select("*").eq("spot_id",id).order("created_at",{ascending:false}),supabase.from("spot_comments").select("*").eq("spot_id",id).order("created_at",{ascending:false})]);
    if(!spot)notFound();const action=saveSpot.bind(null,id),remove=deleteSpot.bind(null,id),average=reviews?.length?reviews.reduce((sum,row)=>sum+row.rating,0)/reviews.length:null;
    return <main className={styles.content}><header className={styles.pageHeader}><div><span>Spot editor</span><h1>{spot.name}</h1><p>{reviews?.length??0} ratings{average?` · ${average.toFixed(1)} average`:""} · {media?.length??0} media · {comments?.length??0} comments</p></div></header><form action={action} className={styles.formGrid}><section className={styles.panel}><h2>Details</h2><div className={styles.field}><label>Name</label><input name="name" defaultValue={spot.name} required/></div><div className={styles.field}><label>Slug</label><input name="slug" defaultValue={spot.slug} required/></div><div className={styles.field}><label>Description</label><textarea name="description" defaultValue={spot.description} required/></div><div className={styles.field}><label>Map</label><select name="map_id" defaultValue={spot.map_id}>{maps?.map(map=><option value={map.id} key={map.id}>{map.name}</option>)}</select></div><div className={styles.field}><label>District</label><select name="district_id" defaultValue={spot.district_id??""}><option value="">Unassigned</option>{districts?.filter(d=>d.map_id===spot.map_id).map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></div><div className={styles.field}><label>Category</label><select name="category" defaultValue={spot.category}><option value="community">Community</option><option value="popular">Popular</option><option value="city-echo">Real-World Inspired</option></select></div><div className={styles.field}><label>Position [x,y]</label><input name="position" defaultValue={JSON.stringify(spot.position)}/></div><div className={styles.field}><label>Status</label><select name="is_published" defaultValue={String(spot.is_published)}><option value="false">Needs review / draft</option><option value="true">Published</option></select></div></section><div className={styles.formActions}><button type="submit">Save spot</button><button type="submit" formAction={remove}>Delete spot</button></div></form>
    <section className={styles.panel}><h2>Media moderation</h2>{media?.length?<div className={styles.categoryGrid}>{media.map(item=>{const url=supabase.storage.from("spot-media").getPublicUrl(item.storage_path).data.publicUrl;return <article className={styles.categoryCard} key={item.id}><header><div><h2>{item.media_type}</h2><small>{item.is_published?"Published":"Pending"}{item.is_cover?" · Cover":""}</small></div></header>{item.media_type==="image"?<img src={url} alt={item.caption??"Spot upload"}/>:<video src={url} controls/>}<p>{item.caption??"No caption"}</p><footer><form action={setMediaPublished.bind(null,item.id,id,!item.is_published)}><button>{item.is_published?"Unpublish":"Approve"}</button></form><form action={setMediaCover.bind(null,item.id,id)}><button>Make cover</button></form><form action={deleteMedia.bind(null,item.id,id)}><button>Delete</button></form></footer></article>})}</div>:<p>No media submissions.</p>}</section>
    <section className={styles.panel}><h2>Comments</h2>{comments?.map(comment=><article className={styles.categoryCard} key={comment.id}><p>{comment.body}</p><footer>{new Date(comment.created_at).toLocaleString()}<form action={deleteComment.bind(null,comment.id,id)}><button>Delete</button></form></footer></article>)}{!comments?.length&&<p>No comments.</p>}</section></main>;
}
