"use client";
import { useState } from "react";
import Link from "next/link";
import { Heart,MessageCircle,Send,Share2,X } from "lucide-react";
import { addSocialPostComment,toggleSocialPostLike } from "@/app/(site)/social/actions";
import { Drawer,DrawerClose,DrawerContent,DrawerDescription,DrawerHeader,DrawerTitle } from "@/components/ui/drawer";
import { useToast } from "@/components/ui/toast";
import type { SocialPost } from "@/lib/social/get-posts";
import styles from "./social.module.scss";
export function PostInteractions({post,signedIn}:{post:SocialPost;signedIn:boolean}){const toast=useToast(),[liked,setLiked]=useState(post.likedByViewer),[likes,setLikes]=useState(post.likes),[comments,setComments]=useState(post.commentItems),[commentsOpen,setCommentsOpen]=useState(false),[comment,setComment]=useState(""),[busy,setBusy]=useState(false);
const toggleLike=async()=>{if(!signedIn){toast({kind:"info",title:"Sign in to like posts",description:"Create an account or sign in to join the conversation."});return}const before=liked;setLiked(!before);setLikes(count=>count+(before?-1:1));const result=await toggleSocialPostLike(post.id);if(!result.ok){setLiked(before);setLikes(count=>count+(before?1:-1));toast({kind:"error",title:"Couldn’t update like",description:result.message})}};
const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!signedIn){toast({kind:"info",title:"Sign in to comment"});return}setBusy(true);const result=await addSocialPostComment(post.id,comment);setBusy(false);if(!result.ok||!result.comment){toast({kind:"error",title:"Couldn’t post comment",description:result.message});return}setComments(items=>[...items,result.comment!]);setComment("");toast({kind:"success",title:"Comment posted"})};
const share=async()=>{const url=`${window.location.origin}/social#post-${post.id}`;try{if(navigator.share)await navigator.share({title:`Post by ${post.author.name}`,text:post.body.slice(0,140),url});else{await navigator.clipboard.writeText(url);toast({kind:"success",title:"Link copied"})}}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;toast({kind:"error",title:"Couldn’t share this post"})}};
return <><footer className={styles.postActions}><button type="button" onClick={toggleLike} data-active={liked} aria-pressed={liked}><Heart fill={liked?"currentColor":"none"}/> {likes}</button><button type="button" onClick={()=>setCommentsOpen(true)}><MessageCircle/> {comments.length}</button><button type="button" onClick={share}><Share2/> Share</button></footer><Drawer open={commentsOpen} onOpenChange={setCommentsOpen} showSwipeHandle><DrawerContent className={styles.commentsDrawer}><DrawerHeader><div><DrawerTitle>Comments</DrawerTitle><DrawerDescription>{comments.length} {comments.length===1?"reply":"replies"} to this post</DrawerDescription></div><DrawerClose aria-label="Close comments"><X/></DrawerClose></DrawerHeader><div className={styles.commentList}>{comments.map(item=><article key={item.id}><span>{item.author.name.slice(0,1).toUpperCase()}</span><div><strong>{item.author.name} <small>@{item.author.handle}</small></strong><p>{item.body}</p><time>{new Date(item.createdAt).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short"})}</time></div></article>)}{!comments.length&&<p className={styles.emptyComments}>No comments yet. Start the conversation.</p>}</div>{signedIn?<form className={styles.commentComposer} onSubmit={submit}><textarea value={comment} onChange={event=>setComment(event.target.value)} required maxLength={2000} placeholder="Write a comment…"/><button disabled={busy}><Send/>{busy?"Posting…":"Post comment"}</button></form>:<div className={styles.commentSignIn}><p>Sign in to add a comment.</p><Link href="/account/sign-in?next=/social">Sign in</Link></div>}</DrawerContent></Drawer></>}
